### ISSUE TITLE
Data is not stored on MongoDB through an Orion Context Broker

### ISSUE THREAD

**Issue by janaka1984** [OpenMTC/OpenMTC#10] opened 2018-06-15 04:47 UTC
Hi @ronald-steinke 

**i have executed docker-compose.yml file (https://github.com/OpenMTC/OpenMTC/blob/master/apps/OrionContextBroker/README.md). Then it is deployed related docker container.  When i see logs, i could see following before create sample data on mongodb (e.g "TESTTENANT-bath","TESTTENANT-kitchen")**

> mongo    | 2018-06-15T04:10:44.266+0000 I NETWORK  [thread1] waiting for connections on port 27017

**Also when  i ran following curl script to store data at the Orion CB as describe in README file, then output is empty and can not see any data on mongdb** 

> curl -X POST localhost:18000/onem2m/ -H "Content-Type: application/vnd.onem2m-res+json" -d '{"m2m:ae": {"rn": "EXAMPLE_APP_NAME", "api": "placeholder", "rr": "TRUE"}}'
> 
> curl -X POST localhost:18000/onem2m/EXAMPLE_APP_NAME/ -H "Content-Type: application/vnd.onem2m-res+json" -d '{"m2m:cnt": {"rn": "EXAMPLE_DEVICE_NAME", "lbl":["openmtc:device"]}}'
> 
> curl -X POST localhost:18000/onem2m/EXAMPLE_APP_NAME/EXAMPLE_DEVICE_NAME/ -H "Content-Type: application/vnd.onem2m-res+json" -d '{"m2m:cnt": {"rn": "EXAMPLE_MEASUREMENT_NAME", "lbl":["openmtc:sensor_data"]}}'
> 
> curl -X POST localhost:18000/onem2m/EXAMPLE_APP_NAME/EXAMPLE_DEVICE_NAME/EXAMPLE_MEASUREMENT_NAME/ -H "Content-Type: application/vnd.onem2m-res+json" -d '{"m2m:cin": {"con": "eyJuIjogInRlbXBlcmF0dXJlIiwgImJuIjogIm9wZW5tdGM6emlnYmVlOnRlbXAiLCAidiI6IDI0LCAidSI6ICJDZWwiLCAidCI6ICIyMDE3LTA0LTEzIDEyOjQ1OjEyLjc4NzIzOSJ9Cg==", "cnf": "application/json:1"}}'
> 
> curl localhost:1026/v2/entities/ | jq '.'

**Also i have tried to run  ./apps/influx-db separately, but it also returned following error.**

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/privacy/src/OpenMTC/apps/InfluxDB/src/influxdb/__main__.py", line 5, in <module>
>     from .influx_db import InfluxDB
>   File "/home/privacy/src/OpenMTC/apps/InfluxDB/src/influxdb/influx_db.py", line 2, in <module>
>     from connector import InfluxDBConnector
>   File "/home/privacy/src/OpenMTC/apps/InfluxDB/src/influxdb/connector.py", line 3, in <module>
>     from influxdb import InfluxDBClient
> ImportError: cannot import name InfluxDBClient

**can i know what is the issue with OCB and mongodb connection ?**

Regards 
Janaka

**Comment by ckl-fokus** [comment] 2018-06-20 16:53
Hi @janaka1984,

Thanks for your feedback and sorry for the late reply.

I fixed the problem with the influxdb app. It had to be renamed to "influxdb-app". Therefore you should be able to start it via:

```
./apps/influxdb-app 
```

Also, I have corrected the curl scipts in the documentation of the OCB app. The scripts should work now.

But I was not able to reproduce any problems with the mongoDB and the OCB. The log message you mentioned ([...]waiting for connections[...]) is perfectly normal. 
Maybe you can test the setup again with the newest version. If the problem with the mongoDB is not solved, it would be nice if you could send me the output of:

```
docker logs <MONGODB CONTAINER ID>
docker logs <OCB CONTAINER ID>
```

**Comment by janaka1984** [comment] 2018-06-27 10:58
Hi @ckl-fokus 

i could connect influxdb into openmtc gateway and backend seperatly . i need to know how subscribe to OpenMTC data and tranfer it to an instance of the InfluxDB?  where data model format is defined? or do i need to create my own python executable file as same as "onem2m-gui-sensors-final.py"

>  measurement: data_senml["n"] (example: vehiclecount)
> * time: data_senml["t"]
> * tags:
>   * application name (example: loadgen)
>   * device name (example: parking_space)
>   * sensor name (example: totalspaces)
>   * sensor labels (example: "openmtc:sensor")
>   * device labels (example: "openmtc:device")
> * fields:
>   * value: data_senml["v"]
>   * bn: data_senml["bn"]
>   * unit: data_senml["u"]

Regards
Janaka

**Comment by ckl-fokus** [comment] 2018-06-28 08:30
Is it possible that you have deleted your last comment? I got a notification, but I can not see your comment here. Maybe the issue is solved?

**Comment by janaka1984** [comment] 2018-06-28 09:07
yes i could find solution. actually i thought it is the issue. but after find where influxdb is called from openmtc , i deleted it .

still pending to check OCB and mongodb , after check it , i will give feedback

**Comment by janaka1984** [comment] 2018-07-03 08:38
Hi @ckl-fokus 
Following curl script does not return value as mentioned on README file

> curl -X "GET" localhost:18000/~/mn-cse-1/onem2m/CUL868IPE/S300TH_1/temperature/latest -s | \
>   jq -r '."m2m:cin".con' | \
>   base64 -d | jq '.'

> curl localhost:1026/v2/entities/mn-cse-1-Wohnzimmer/ -s -S | jq '."temperature"'

> curl localhost:1026/v2/entities/mn-cse-1-Bad/attrs -s -S \
>      --header 'Content-Type: application/json' \
>      -X PATCH -d @- <<EOF
> {
>   "cmd": {
>     "value": "ON",
>     "type": "String"
>   }
> }
> EOF

> curl -X "GET" localhost:18000/~/mn-cse-1/onem2m/CUL868IPE/FS20_ST3_16108_1/switch/latest -s | jq '."m2m:cin".con'

But it is possible to connect OCB and mongodb and store data  on db.

When run './apps/orion-context-broker  -v' to use OCB without docker , it is connected to openmtc backend worked.                                                                                                                                          but i can not see any parameter  on config.json to connect Mongodb, can you give hint for this?

**Comment by ckl-fokus** [comment] 2018-07-03 12:22
Hi @janaka1984,

Thanks for your valueable feedback. 

**about the curl commands:**
There were still remaining mistakes in the curl commands. They should be fixed now. 

**about the mongodb config option**
Maybe you misunderstood something about the architecture. The command './apps/orion-context-broker -v' will not start the Orion Context Broker itself, instead it will start the OpenMTC app, which will connect OpenMTC to the Orion Context Broker. If you have a look at the architecture picture ![here](https://github.com/OpenMTC/OpenMTC/blob/master/apps/OrionContextBroker/README.md#example-setup-with-docker), you will see that the app is not directly connected to the MongoDB. Therefore there is no need to configure something in regard to the MongoDB.
If you want to start the Orion Context Broker itself without using Docker, you can check the ![official documentation by Fiware](https://fiware-orion.readthedocs.io/en/master/).

**Comment by ckl-fokus** [comment] 2018-07-12 08:30
Hi @janaka1984,

Is the issue solved for you?

**Comment by janaka1984** [comment] 2018-07-12 09:14
hi @ckl-fokus 

problem was solved , thank you very much for your support

**Closed as completed** 2018-07-12 10:35 UTC
