### ISSUE TITLE
Can not build docker container by using  gateway Image on debian:jessie

### ISSUE THREAD

**Issue by janaka1984** [OpenMTC/OpenMTC#7] opened 2018-05-17 12:36 UTC
## **I have used "./create-binary-docker gateway" command to build  OpenMTC_gateway Image on debian:jessie.  Then it return following error** 

 Step 5/7 : RUN pip install --upgrade --requirement /tmp/requirements.txt
 ---> Running in cab3256162de
Downloading/unpacking urllib3 from https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl#sha256=06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b (from -r /tmp/requirements.txt (line 1))
Downloading/unpacking gevent>=1.0 (from -r /tmp/requirements.txt (line 2))
  Running setup.py (path:/tmp/pip-build-FwbeYy/gevent/setup.py) egg_info for package gevent
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-FwbeYy/gevent/setup.py", line 406, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "/tmp/pip-build-FwbeYy/gevent/setup.py", line 390, in run_setup
        "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 603, in resolve
        requirements = list(requirements)[::-1]
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
        "version spec")
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2697, in scan_list
        raise ValueError(msg, line, "at", line[p:])
    ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-FwbeYy/gevent/setup.py", line 406, in <module>

    run_setup(EXT_MODULES, run_make=_BUILDING)

  File "/tmp/pip-build-FwbeYy/gevent/setup.py", line 390, in run_setup

    "signal_os_incompat = gevent.monkey:_subscribe_signal_os",

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 603, in resolve

    requirements = list(requirements)[::-1]

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements

    "version spec")

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2697, in scan_list

    raise ValueError(msg, line, "at", line[p:])

ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")

## **Please give me hint to solve this issue**

ERROR:openmtc_gevent.main:Error loading plugin HTTPTransportPlugin: No module named wsgi
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openmtc_gevent/main.py", line 96, in load_plugin
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openmtc_cse/plugins/transport_gevent_http/__init__.py", line 9, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openmtc_cse/plugins/transport_gevent_http/wsgi.py", line 9, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named wsgi
ERROR:openmtc_gevent.main:Error during startup
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openmtc_gevent/main.py", line 387, in main
  File "/usr/local/lib/python2.7/dist-packages/openmtc_gevent/main.py", line 131, in load_plugins
  File "/usr/local/lib/python2.7/dist-packages/openmtc_gevent/main.py", line 124, in load_plugin
Exception: Error loading plugin HTTPTransportPlugin: No module named wsgi

## **my docker version  is mentioned  below**

> Client:
>  Version:      18.03.1-ce
>  API version:  1.37
>  Go version:   go1.9.5
>  Git commit:   9ee9f40
>  Built:        Thu Apr 26 07:17:20 2018
>  OS/Arch:      linux/amd64
>  Experimental: false
>  Orchestrator: swarm
> 
> Server:
>  Engine:
>   Version:      18.03.1-ce
>   API version:  1.37 (minimum version 1.12)
>   Go version:   go1.9.5
>   Git commit:   9ee9f40
>   Built:        Thu Apr 26 07:15:30 2018
>   OS/Arch:      linux/amd64
>   Experimental: false

Thanks

**Comment by rst-fokus** [comment] 2018-05-22 11:24
Hello @janaka1984 ,

Thanks for noticing. The issue is fixed with aecf7c0c02fa02f8bea727a82bcace70c1bcab76.

Please let me know, if I can close the issue.

Best,
Ronald

**Comment by janaka1984** [comment] 2018-05-22 17:32
Hi @rst-fokus - Ronald 

Thank you very much for fixing the issue. Now it works

i found only  one issue when build gateway
./create-binary-docker gateway

debconf: delaying package configuration, since apt-utils is not installed

Regards
Janaka

**Comment by rst-fokus** [comment] 2018-05-23 15:03
Hi Janaka,

this is just a warning and is not a problem. So I will close the issue then.

Best,
Ronald

**Closed as completed by rst-fokus** 2018-05-23 15:03 UTC
